### ISSUE TITLE
bounding box includes more than one article of clothing.

### ISSUE THREAD

**Issue by vlsd** [datascopeanalytics/DeepProduct#3]
The image in question is http://dopeornope.datascopeanalytics.com/static/to_dropbox/DeepFashion/img/Pleated_Ponte_Knit_Dress/img_00000057_bbox.png

**Comment by ZombieSocrates** [comment]
Bounding boxes are set by the annotators of the database and weren't determined by us. My main hope is that the cases where they look weird (like this one) are generally offset by the ones where they are pretty clear.
